# Generated by Django 3.2.3 on 2021-07-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte', models.IntegerField(unique=True)),
                ('montant', models.FloatField(null=True)),
                ('Nom', models.CharField(default='', max_length=100, null=True)),
                ('prenom', models.CharField(default='', max_length=100, null=True)),
                ('telephone', models.CharField(max_length=12, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
